MyProject/MyApp/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('' , views.home.as_view() , name='home'),
    path('all_candidates/' , views.all_candidates.as_view() , name='all_candidates'),
    path('candidate_info/<int:pk>' , views.candidate_info.as_view() , name='candidate_info'),
    path('about/' , views.about.as_view() , name='about'),
    path('contact/' , views.contact.as_view() , name='contact'),

]

MyProject/MyProject/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('MyApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)



MyProject/MyApp/models.py

from django.db import models

# Create your models here.

city_choices = [('Mumbai','Mumbai') ,('Delhi','Delhi'),('Pune','Pune'),('Nasik','Nasik'),('Auranabad','Auranabad'),('Bangluru','Bangluru'),('Bangluru','Bangluru'),('Basti','Basti'),('Lonavala','Lonavala')]

state_choices = (("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry"))

class Resume(models.Model):
    fname = models.CharField(max_length=100) 
    lname = models.CharField(max_length=100)
    dob = models.DateField(auto_now=False , auto_now_add=False)
    gender = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    locality = models.CharField(max_length=100)
    city = models.CharField(choices=city_choices , max_length=100)
    state = models.CharField(choices=state_choices , max_length=100)
    pin = models.PositiveIntegerField()
    mobile = models.PositiveIntegerField()
    email = models.EmailField()
    programming_language = models.CharField(max_length=100)
    profile_photo =  models.ImageField(upload_to = 'Profile_photo' , blank = True)


MyProject/MyApp/forms.py
from cProfile import label
from secrets import choice
from django import forms
from .models import Resume

gender_choices = [('Male','Male'),('Female','Female'),('Not To Prefer','Not To Prefer')]

prog_choices = [('Python','Python'),('Java','Java'),('C','C'),('C++','C++'),('Sql','Sql'),('Css','Css'),('Html','Html')]



class ResumeForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=gender_choices , widget=forms.RadioSelect)
    programming_language = forms.MultipleChoiceField(choices=prog_choices , widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Resume
        
        fields = ['fname' ,'lname','dob','gender','language','locality','city','state' ,'pin','mobile','email','programming_language','profile_photo']

        labels = {
            'fname': 'First Name',
            'lname' : 'Last Name',
            'dob':'Date Of Birth (dd/mm/yyy)',
            'pin':'Pin Code',
            'mobile':'Contact No',
            'email':'Email-ID',
        }

        widgets = {
            'fname':forms.TextInput(attrs={'class':'form-control'}),
            'lname':forms.TextInput(attrs={'class':'form-control'}),
            'dob' : forms.DateInput(attrs={'class':'form-control w-50'}),
            'language':forms.TextInput(attrs={'class':'form-control'}),
            'locality':forms.TextInput(attrs={'class':'form-control'}),
            'city' : forms.Select(attrs={'class':'form-control w-50'}),
            'state' : forms.Select(attrs={'class':'form-control w-50'}),
            'pin' : forms.TextInput(attrs={'class':'form-control'}),
            'mobile' : forms.TextInput(attrs={'class' : 'form-control'}),
            'email': forms.TextInput(attrs={'class' : 'form-control'}),
        }

MyProject/MyApp/views.py
from django.shortcuts import render ,redirect
from django.views import View
from .forms import ResumeForm
from .models import Resume

# Create your views here.

class home(View):
    def get(self , request):
        print("Class Home method get ...")

        form = ResumeForm()
        
        return render(request , 'MyApp/home.html' , {'form':form})

    def post(self , request):
        print("Class Home method Post ...")
        form = ResumeForm(request.POST , request.FILES)
        if form.is_valid():
            print("Form Validated ...")
            form.save()
            print("Forms saved Successfully ..")
            return redirect('home')





class all_candidates(View):
    def get(self , request):
        print("Class all_candidates method get ...")
        data = Resume.objects.all()

        return render(request , 'MyApp/all_candidates.html' , {'data':data})

    def post(self , request):
        print("Class all_candidates method Post ...")
        data = Resume.objects.all()
        return render(request , 'MyApp/all_candidates.html' , {'data':data})





class candidate_info(View):
    def get(self , request , pk):
        print("Class candidate_info method get ...")

        data = Resume.objects.get(pk = pk)
        return render(request , 'MyApp/candidate_info.html' , {'d' : data})

    def post(self , request):
        print("Class candidate_info method Post ...")
        return render(request , 'MyApp/candidate_info.html')





class about(View):
    def get(self , request):
        print("Class about method get ...")
        return render(request , 'MyApp/about.html')

    def post(self , request):
        print("Class about method Post ...")
        return render(request , 'MyApp/about.html')






class contact(View):
    def get(self , request):
        print("Class Contact method get ...")
        return render(request , 'MyApp/contact.html')

    def post(self , request):
        print("Class contact method Post ...")
        return render(request , 'MyApp/contact.html')

MyProject/templates/MyApp/about.html
{% extends 'MyApp/base.html' %}
{% load static %}


{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}


{% block title %}
<title>About Page </title>
{% endblock title %}


{% block body %}
{% endblock body %}

MyProject/templates/MyApp/all_candidates.html
{% extends 'MyApp/base.html' %}
{% load static %}


{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}


{% block title %}
<title>All Candidates Page </title>
{% endblock title %}


{% block body %}
<div class="container">
    <div class="container text-center shadow mb-3">
        <h1 class="display-5 text-primary">All Candidates</h1>
    </div>

    <div class="container mb-3 p-5 shadow">
        {% for d in data %}
            <div class="container p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{{ d.profile_photo.url }}" alt="No Image"  height="200px">
                        
                    </div>

                    <div class="col-4 m-3 p-3">
                        <a href="{% url 'candidate_info' d.id %}">{{d.email}}</a>
                        
                    </div>


                </div>

            </div>
        {% endfor %}
        
    </div>


</div>
{% endblock body %}

MyProject/templates/MyApp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <!-- icon bootstrap Link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    {% block css %}
    {% endblock css %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock js %}


    {% block title %}
    {% endblock title %}


    
</head>
<body>
    {% include 'MyApp/nav_bar.html' %}

    <div class="container">

        {% block body %}

        {% endblock body %}
    </div>



</body>
</html>

MyProject/templates/MyApp/candidate_info.html
{% extends 'MyApp/base.html' %}
{% load static %}


{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}


{% block title %}
<title>Candidate Info Page </title>
{% endblock title %}


{% block body %}
<div class="container">
    <div class="container text-center shadow mb-3">
        <h1 class="display-5 text-primary">Candidate Information</h1>
    </div>

    <div class="container mb-3 p-5 shadow">
        
        <div class="container border-bottom pb-5">
            <img src="{{ d.profile_photo.url }}" alt="No Profile Phoro" height="200px"> 
        </div>
        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">First Name :</label> <span>{{d.fname}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Last Name :</label> <span>{{d.lname}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Date Of Birth :</label> <span>{{d.dob}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Gender :</label> <span>{{d.gender}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Language :</label> <span>{{d.language}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Locality :</label> <span>{{d.locality}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">City :</label> <span>{{d.city}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">State :</label> <span>{{d.state}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Contact No. :</label> <span>{{d.mobile}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Email-ID :</label> <span>{{d.email}}</span>
        </div>

        <div class="container border-bottom pb-3">
            <label class="fw-bolder ">Programming Language :</label> <span>{{d.programming_language}}
            </span>
        </div>
        


</div>
{% endblock body %}

MyProject/templates/MyApp/contact.html
{% extends 'MyApp/base.html' %}
{% load static %}


{% block css %}
{% endblock css %}

{% block js %}
{% endblock js %}


{% block title %}
<title>Contact Page </title>
{% endblock title %}


{% block body %}
{% endblock body %}

MyProject/templates/MyApp/home.html
{% extends 'MyApp/base.html' %}
{% load static %}


{% block css %}
{% endblock css %}

{% block js %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $(function () {
        $("#id_dob").datepicker();
        $("#anim").on("change", function () {
            $("#id_dob").datepicker("option", "showAnim", $(this).val());
        });
    });
</script>



{% endblock js %}


{% block title %}
<title>Home Page </title>
{% endblock title %}


{% block body %}
<div class="container">
    <div class="container text-center shadow mb-3">
        <h1 class="display-5 text-primary">Resume Form</h1>
    </div>

    <div class="container mb-3 p-5 shadow">
        <form action="{% url 'home' %}" method="post" enctype="multipart/form-data" class="p-5">
            {% csrf_token %}

            {% for fm in form %}
            <div class="form-group mb-3">
                <span class="fw-bold">{{fm.label_tag}}</span>
                {{fm}}
            </div>

            {% endfor %}
            <div class="form-group mb-3">
                <button class="btn btn-primary" type="submit">Submit</button>
                <button class="btn btn-success" type="reset">Reset</button>
            </div>


        </form>



    </div>


</div>
{% endblock body %}

MyProject/templates/MyApp/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}"><h3><i class="bi bi-house-fill"></i></h3></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'all_candidates' %}">All Candidates</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              All Options
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'all_candidates' %}">All Candidates</a></li>
              <li><a class="dropdown-item" href="{% url 'contact' %}">Contact Us</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'about' %}">About Us</a></li>
            </ul>
          </li>
          
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>